quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
      driver: org.postgresql.Driver
    devservices:
      enabled: false

  http:
    cors:
      ~: true
      methods: GET,POST,PUT,DELETE,OPTIONS
      origins: http://localhost:5173
      headers: Accept,Authorization,Content-Type
      exposed-headers: Location

  resteasy-reactive:
    path: /api

  smallrye-openapi:
    path: /openapi
    info:
      title: API de Controle Financeiro
      version: "1.0.0"
      description: API REST para gerenciar cartões e despesas pessoais.

  log:
    category:
      "com.br.hmdevelop.financeiro":
        level: DEBUG